name: Deploy cli to homebrew
on:
  workflow_call:
    inputs:
      LATEST_RELEASE:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      LATEST_RELEASE: ${{ inputs.LATEST_RELEASE }}
    
    steps:
      - name: Checkout cli-public repo 
        uses: actions/checkout@v3

      - name: Setup
        run: |
          VERSION=$(echo "${LATEST_RELEASE//v}")
          echo "ZIP_SHA=$(sha256sum ./binaries/iac-mac_os-$VERSION.zip | awk '{print $1}')" >> $GITHUB_ENV

      - name: Sync homebrew with upstream
        uses: TobKed/github-forks-sync-action@v0.2.0
        with:
          github_token: ${{ secrets.PAT }}
          upstream_repository: Homebrew/homebrew-cask
          target_repository: oak9io/homebrew-cask

      - name: Checkout homebrew fork
        uses: actions/checkout@v3
        with:
          repository: oak9io/homebrew-cask
          path: homebrew-cask

      - uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
        with:
          repository_owner: oak9io
          repository_name: homebrew-cask
          new_branch_name: $LATEST_RELEASE
          access_token: ${{ secrets.PAT }}

      - name: Update oak9 homebrew file
        run: |
          VERSION=$(echo "${LATEST_RELEASE//v}")
          sed -i'' -e "s/  sha256.*/  sha256 \"$ZIP_SHA\"/" ./homebrew-cask/Casks/oak9.rb
          sed -i'' -e "s/  version.*/  version \"$VERSION\"/" ./homebrew-cask/Casks/oak9.rb
          cat ./homebrew-cask/Casks/oak9.rb
