name: oak9 cli Package Management Workflow
run-name: ${{ github.actor }} oak9 cli Package Management Workflow

on:
  push
#Once tested enabled on release
#on:
#  release:
#    types: created

jobs:
  package_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch latest release version
        run: |
          echo "LATEST_RELEASE=$(git tag --list 'v*' | tail -1)" >> $GITHUB_ENV
          git tag --list 'v*' | tail -1     
      - name: Test
        run: echo ${{ env.LATEST_RELEASE }}


