name: oak9 cli Package Management Workflow
run-name: ${{ github.actor }} oak9 cli Package Management Workflow
on:
  workflow_dispatch:

  push:

#Once tested enabled on release
#on:
#  release:
#    types: created

jobs:
  package_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch latest release version
        run: |
          echo "LATEST_RELEASE=$(git tag --list 'v*' | tail -1)" >> $GITHUB_ENV
      
      - name: Homebrew
        uses: ./.github/workflows/homebrew.yml
        with:
          LATEST_RELEASE: ${{ env.LATEST_RELEASE }}

